# List of build configurations for Android.
# The first configuration that matches the repository name will be used.
repo_configurations:
  - # Default configuration for Android repositories
    builds:
      - directory: "."
        commands:
          - "git pull origin master"
          - "./gradlew clean"
          - "./gradlew installDebug"