git_command: "git pull origin master"

# List of build configurations.
# The first configuration that matches the repository name will be used.
# If no repository name matches, the first configuration without a repo_name is used as the default.
repo_configurations:
  - repo_name: "ios-ui-tests" # Optional: for a specific repository
    builds:
      - directory: "MCOM"
        commands:
          - "bundler install"
          - "fastlane regenerate_project"
          - "pod update"
      - directory: "BCOM"
        commands:
          - "bundler install"
          - "fastlane regenerate_project"
          - "pod update"

  - # Default configuration for other iOS repositories
    builds:
      - directory: "." # Assumes build happens at the root
        commands:
          - "pod install"
