# The active build profile. Set this to one of the profiles defined below (e.g., "ios", "android").
active_profile: "ios"

# ----------------------------------------------------------------------------------------
# Build Profiles
#
# Each profile defines a complete build environment, including the base directory to scan,
# project filtering rules, and build priorities.
# ----------------------------------------------------------------------------------------
build_profiles:
  ios:
    base_directory: "/Users/srinivasan.arulsivam/projects/ios"
    include_names: "ios_app"
    exclude_names: ""
    include_pattern: ".*"
    exclude_pattern: ".*test.*"
    build_priority: ""

  android:
    base_directory: "/Users/srinivasan.arulsivam/projects/android"
    include_names: "android-app"
    exclude_names: ""
    include_pattern: ".*"
    exclude_pattern: ""
    build_priority: ""

  services:
    base_directory: "/Users/srinivasan.arulsivam/projects/xapi"
    include_names: ""
    exclude_names: "msp-mobile-app-core,mobile-core-xapi"
    include_pattern: ".*mobile.*|.*platform.*"
    exclude_pattern: ".*test.*"
    build_priority: "macys-platform-spring,mobile_xapi_common"

  automation:
    base_directory: "/Users/srinivasan.arulsivam/projects/automation"
    include_names: "ios-ui-tests"
    exclude_names: ""
    include_pattern: ""
    exclude_pattern: ""
    build_priority: ""

# --- Global Settings ---

project_overrides:
  xapi:
    build_command: "./custom-spring-boot-build.sh"

git:
  pull_command: "git pull origin master"

logging:
  enabled: true
