# List of build configurations.
# The first configuration that matches the repository name will be used.
# If no repository name matches, the first configuration without a repo_name is used as the default.
repo_configurations:
  - repo_name: "ios_app" # Optional: for a specific repository
    builds:
      - directory: "."
        commands:
          - "git reset --hard"
          - "git fetch"
          - "git checkout master"
          - "git pull origin master"
      - directory: "HostApp"
        commands:
          - "pod repo remove gitlab-macys-mobile-ios-podspecs"
          - "pod repo update fds-mobile-ios-podspecs"
          - "pod cache clean --all"
          - "fastlane install"
      - directory: "BAPP/HostApp"
        commands:
          - "bundle install"
          - "fastlane install"

  - # Default configuration for other iOS repositories
    builds:
      - directory: "."
        commands:
          - "git pull origin master"
          - "pod install"
