# List of build configurations for Services.
# The first configuration that matches the repository name will be used.
repo_configurations:
  - # Default configuration for all service repositories
    builds:
      - directory: "."
        commands:
          - "git pull origin master"
          - "mvn clean"
          - "mvn install -Dmaven.test.skip=true"